title: notsaad's webpage
author: saad mazhar
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  this is my webpage that i created in computer science on September 6th, 2018.

# social links
twitter_username: @notsaadm
instagram_userame: @notsaad
github_username:  notsaad

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
